# Generated by Django 2.2.3 on 2019-08-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stu',
            table='test_table',
        ),
    ]
