# Generated by Django 2.2.3 on 2019-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190819_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='stu',
            table=None,
        ),
    ]
