# Generated by Django 2.2.3 on 2019-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190819_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
