# Generated by Django 2.2.3 on 2019-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_configinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
