# Generated by Django 2.2.3 on 2019-08-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190820_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configinfo',
            name='url',
            field=models.TextField(default='', null=True, verbose_name='爬取链接'),
        ),
        migrations.AlterField(
            model_name='stu',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
