# Generated by Django 2.2.3 on 2019-08-22 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_stu_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='configinfo',
            name='config_createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_css',
            field=models.CharField(max_length=255, null=True, verbose_name='爬取css'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_people',
            field=models.CharField(max_length=100, null=True, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_table',
            field=models.CharField(max_length=100, null=True, verbose_name='存入表名'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_type',
            field=models.CharField(max_length=100, null=True, verbose_name='爬取类型'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
    ]
