# Generated by Django 2.2.3 on 2019-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190822_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='url',
            field=models.TextField(default='', verbose_name='爬取链接'),
        ),
    ]
