# Generated by Django 2.2.3 on 2019-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_stu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configinfo',
            name='config_css',
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_css1',
            field=models.CharField(max_length=255, null=True, verbose_name='爬取css1'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_css2',
            field=models.CharField(max_length=255, null=True, verbose_name='爬取css2'),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='config_status',
            field=models.IntegerField(default=0, max_length=10, verbose_name='网页类型（动态或静态）'),
        ),
    ]
